### ISSUE TITLE
Broken lectures site & Alternative lecture hosting

### ISSUE THREAD

**Issue by dylan-thinnes** [compsoc-edinburgh/betterinformatics#41]
http://podcast.is.ed.ac.uk:8080 , where the lectures used to be hosted for the site at http://groups.inf.ed.ac.uk/vision/VIDEO/ , is down. I tested both from my local PC and an amazon EC2 instance. Do we know how/why this happened and if the lectures will be available again soon?

Also, I have an alternative lecture hosting solution I wrote at https://lectures.dylant.org, temporary password for the time being is "Appleton"
Could someone take a look and tell what they think? Could this serve as a good alternative?

**Comment by qaisjp** [comment]
I know we already discussed this in person, but for more detail / the others reading this:

-----

Those are for legacy lecture recordings systems. Feel free to share your website wherever.

If you end up building something slightly more automated (... and if it's possible to use source URLs from Echo365, rather than S3), we could put it directly on Better Informatics.

**Comment by rphi** [comment]
It *looks* doable to extract the videos from Echo360, albeit very much unsupported... They are just .mp4s hosted on S3. Looks like there is some access token stuff going on but also the urls work in this format too, even without auth in incognito mode:

https://uk-org-echo360-alpprod-eu-west-upload.s3.amazonaws.com/52d5.75f1696a-068b-4ce7-83c0-b03455c0fa36/e96ce60d-3991-4a62-a637-7fd7d2a50fa0/hd1.mp4

In theory that means you could make some kind of browser plugin that just makes its way through the page and extracts those urls and posts those somewhere, but I get the feeling it would still be quite manual considering the fact you'd have to login to the site to view the listings.

![screen shot 2017-12-05 at 13 00 29](https://user-images.githubusercontent.com/8237136/33608454-71f71700-d9bc-11e7-86c2-f217aaba45bf.png)

**Comment by dylan-thinnes** [comment]
@rphi Downloading lectures at these endpoints is very easy, I've been doing it for a while for [SlightlyBetterLectures](lectures.dylant.org). It is very easy to download, just a simple wget, and it would also be easy to link directly to Echo360's backend.
The main issue with the second path though is that lecturers can take down lectures themselves, which would likely break our endpoints pointing at S3, this is why I opted to download. Also there's no guarantee that Echo360 won't reallocate endpoints and completely screw us up.
I wrote a couple tools that can be pasted into the page to withdraw urls and then download and save urls to a database, [available here](https://github.com/dylan-thinnes/slightlybetterlectures/tree/master/utils).

@qaisjp I get that you wouldn't want to be pointing to self-hosting lectures, but this *is* password protected, which at least makes it better than the previous solution.

**Comment by qaisjp** [comment]
The URL shared by @rphi still works, so lets see how long that link lasts. If it lasts until the end of December or so, we can assume that the link will be permanent.

@dylan-thinnes the concern isn't Better Informatics pointing to the content (it's not responsible for anything it _links_ to), or the rehosting itself, it's more about the feasibility of rehosting if the service is expanded.

As @rphi mentions here https://github.com/compsoc-edinburgh/betterinformatics/pull/42#issuecomment-349440612, content could be hosted on Tardis to save S3 fees (Better Informatics itself is hosted on Tardis).

In addition, a lecture would only be taken down for a good reason, so I'm not sure if we should simply rehost because it might be lost. If it's taken down at the end of the year automatically (the university pays for the lecture recording facility, and Echo365 might have some retention policies to save up on S3 fees), then it makes sense to rehost.

These are all just suggestions/ideas for an expansion, not things that _absolutely have to be done_, by the way.

-----

More: if you would like this to be part of Better Informatics, like betterinf.com/lectures or lectures.betterinf.com, we could absolutely put this behind DICE authentication. (in a similar fashion to map.betterinformatics.com)

**Comment by qaisjp** [comment]
@rphi @dylan-thinnes - the original echo365 link works :)

**Comment by rphi** [comment]
RE this message on SlightlyBetterLectures:

> Unfortunately, ready access to lectures has been blocked by Echo360, so there will be no more lecture updates. Sorry everyone. - 180117

I'm not having any issues downloading the mp4s? Just they are no longer on an S3 domain.

**Comment by aptgetmoo** [comment]
Though bandwidth is a major concern, this could eat a lot of storage space over time.
Quick calculations required: conservatively suppose an average 100M/lecture (I think it's around this mark, fnlp lectures tend to be around 80M).

Dimensional analysis:
100M / lecture * 2 lectures / week * 10 weeks / semester => around 2G / course . semester

But the question is: for how many courses would we be storing lectures (I am ignoring the fact that some are probably not recorded)?
If it's for every course in inf1 and inf2 (including maths courses), that will be 7 (inf1) + 7 (inf2), yielding about 24G / year. This is doable, without concern for space.

However, past inf2, [there are a *lot* of courses](http://course.inf.ed.ac.uk/) (maybe around 20 in inf3, 30 in inf4 and 30 in inf5). And while I appreciate they vary wildly in lecture count (and whether they are even recorded at all), it might get prohibitively expensive to store all the content forever.

Does anyone have any thoughts? Storage space is (relatively) cheap, and this feature would obviously be useful, but I feel that this is a particularly high maintenance aspect of BI since we'd be scraping an 'API' subject to change, and if the utilisation is large, I fear for the lifetime of the disks in the rack.

Are inf not keeping a copy of all the lectures somewhere? It seems a bit bonkers for all the traffic to be going out to s3 just for it to come right back to Edinburgh...

**Comment by qaisjp** [comment]
FYI I don't think self hosting lectures should be a first choice as it puts
Better Informatics in a bit of a dodge situation.

**Comment by aptgetmoo** [comment]
I agree. For some reason I misread and thought you were going down that route.

**Comment by livecodealex** [comment]
I personally think that self hosting is a big no no since the IP rights to recordings are University property (maybe even lecturers) and I definitely think it’s not something they would be willing to give/that students should want to take on. But that’s just my two cents

**Comment by qaisjp** [comment]
sorry @dylan-thinnes https://github.com/compsoc-edinburgh/betterinformatics/commit/b878f3c7c63720ba2d6a0b7f084d85b8747fbd8c

**Comment by qaisjp** [comment]
closing this as https://lectures.dylant.org/ no longer exists

It would still be nice to explore lectures and looking into how we can make it easier to use / download, even if it means sharing some sort of greasemonkey script.
